apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-lab22
  labels:
    app: frontend-lab22
spec:
  selector:
    matchLabels:
      app: frontend-lab22
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-lab22
    spec:
      containers:
        - name: frontend-lab22
          image: fabjin/frontend-lab22
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
